//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace basicWeb.SicrisWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PrjOfOrgJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrjOfRsrJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrjByRsrIdsJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrjByIdJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrjByIdsJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProfileOfRsrJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback RsrByIdsJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback RsrOnPrjJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback RsrInOrgJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback CollaborationOfRsrOnPrj1JsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrgByRsrIdsJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrgByIdJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback LecOfRsrJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback CollaborationOfRsrOnBib1OperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateIndexRsrOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateIndexRsr_enOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateIndexPrjOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateIndexPrj_enOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateIndexOrgOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAutocompleteFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::basicWeb.Properties.Settings.Default.basicWeb_SicrisWS_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PrjOfOrgJsonCompletedEventHandler PrjOfOrgJsonCompleted;
        
        /// <remarks/>
        public event PrjOfRsrJsonCompletedEventHandler PrjOfRsrJsonCompleted;
        
        /// <remarks/>
        public event PrjByRsrIdsJsonCompletedEventHandler PrjByRsrIdsJsonCompleted;
        
        /// <remarks/>
        public event PrjByIdJsonCompletedEventHandler PrjByIdJsonCompleted;
        
        /// <remarks/>
        public event PrjByIdsJsonCompletedEventHandler PrjByIdsJsonCompleted;
        
        /// <remarks/>
        public event ProfileOfRsrJsonCompletedEventHandler ProfileOfRsrJsonCompleted;
        
        /// <remarks/>
        public event RsrByIdsJsonCompletedEventHandler RsrByIdsJsonCompleted;
        
        /// <remarks/>
        public event RsrOnPrjJsonCompletedEventHandler RsrOnPrjJsonCompleted;
        
        /// <remarks/>
        public event RsrInOrgJsonCompletedEventHandler RsrInOrgJsonCompleted;
        
        /// <remarks/>
        public event CollaborationOfRsrOnPrj1JsonCompletedEventHandler CollaborationOfRsrOnPrj1JsonCompleted;
        
        /// <remarks/>
        public event OrgByRsrIdsJsonCompletedEventHandler OrgByRsrIdsJsonCompleted;
        
        /// <remarks/>
        public event OrgByIdJsonCompletedEventHandler OrgByIdJsonCompleted;
        
        /// <remarks/>
        public event LecOfRsrJsonCompletedEventHandler LecOfRsrJsonCompleted;
        
        /// <remarks/>
        public event CollaborationOfRsrOnBib1CompletedEventHandler CollaborationOfRsrOnBib1Completed;
        
        /// <remarks/>
        public event CreateIndexRsrCompletedEventHandler CreateIndexRsrCompleted;
        
        /// <remarks/>
        public event CreateIndexRsr_enCompletedEventHandler CreateIndexRsr_enCompleted;
        
        /// <remarks/>
        public event CreateIndexPrjCompletedEventHandler CreateIndexPrjCompleted;
        
        /// <remarks/>
        public event CreateIndexPrj_enCompletedEventHandler CreateIndexPrj_enCompleted;
        
        /// <remarks/>
        public event CreateIndexOrgCompletedEventHandler CreateIndexOrgCompleted;
        
        /// <remarks/>
        public event CreateAutocompleteFileCompletedEventHandler CreateAutocompleteFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrjOfOrgJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrjOfOrgJson(string id) {
            object[] results = this.Invoke("PrjOfOrgJson", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PrjOfOrgJsonAsync(string id) {
            this.PrjOfOrgJsonAsync(id, null);
        }
        
        /// <remarks/>
        public void PrjOfOrgJsonAsync(string id, object userState) {
            if ((this.PrjOfOrgJsonOperationCompleted == null)) {
                this.PrjOfOrgJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrjOfOrgJsonOperationCompleted);
            }
            this.InvokeAsync("PrjOfOrgJson", new object[] {
                        id}, this.PrjOfOrgJsonOperationCompleted, userState);
        }
        
        private void OnPrjOfOrgJsonOperationCompleted(object arg) {
            if ((this.PrjOfOrgJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrjOfOrgJsonCompleted(this, new PrjOfOrgJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrjOfRsrJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrjOfRsrJson(string id) {
            object[] results = this.Invoke("PrjOfRsrJson", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PrjOfRsrJsonAsync(string id) {
            this.PrjOfRsrJsonAsync(id, null);
        }
        
        /// <remarks/>
        public void PrjOfRsrJsonAsync(string id, object userState) {
            if ((this.PrjOfRsrJsonOperationCompleted == null)) {
                this.PrjOfRsrJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrjOfRsrJsonOperationCompleted);
            }
            this.InvokeAsync("PrjOfRsrJson", new object[] {
                        id}, this.PrjOfRsrJsonOperationCompleted, userState);
        }
        
        private void OnPrjOfRsrJsonOperationCompleted(object arg) {
            if ((this.PrjOfRsrJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrjOfRsrJsonCompleted(this, new PrjOfRsrJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrjByRsrIdsJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrjByRsrIdsJson(string[] ids) {
            object[] results = this.Invoke("PrjByRsrIdsJson", new object[] {
                        ids});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PrjByRsrIdsJsonAsync(string[] ids) {
            this.PrjByRsrIdsJsonAsync(ids, null);
        }
        
        /// <remarks/>
        public void PrjByRsrIdsJsonAsync(string[] ids, object userState) {
            if ((this.PrjByRsrIdsJsonOperationCompleted == null)) {
                this.PrjByRsrIdsJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrjByRsrIdsJsonOperationCompleted);
            }
            this.InvokeAsync("PrjByRsrIdsJson", new object[] {
                        ids}, this.PrjByRsrIdsJsonOperationCompleted, userState);
        }
        
        private void OnPrjByRsrIdsJsonOperationCompleted(object arg) {
            if ((this.PrjByRsrIdsJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrjByRsrIdsJsonCompleted(this, new PrjByRsrIdsJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrjByIdJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrjByIdJson(string ids) {
            object[] results = this.Invoke("PrjByIdJson", new object[] {
                        ids});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PrjByIdJsonAsync(string ids) {
            this.PrjByIdJsonAsync(ids, null);
        }
        
        /// <remarks/>
        public void PrjByIdJsonAsync(string ids, object userState) {
            if ((this.PrjByIdJsonOperationCompleted == null)) {
                this.PrjByIdJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrjByIdJsonOperationCompleted);
            }
            this.InvokeAsync("PrjByIdJson", new object[] {
                        ids}, this.PrjByIdJsonOperationCompleted, userState);
        }
        
        private void OnPrjByIdJsonOperationCompleted(object arg) {
            if ((this.PrjByIdJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrjByIdJsonCompleted(this, new PrjByIdJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrjByIdsJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrjByIdsJson(string[] ids) {
            object[] results = this.Invoke("PrjByIdsJson", new object[] {
                        ids});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PrjByIdsJsonAsync(string[] ids) {
            this.PrjByIdsJsonAsync(ids, null);
        }
        
        /// <remarks/>
        public void PrjByIdsJsonAsync(string[] ids, object userState) {
            if ((this.PrjByIdsJsonOperationCompleted == null)) {
                this.PrjByIdsJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrjByIdsJsonOperationCompleted);
            }
            this.InvokeAsync("PrjByIdsJson", new object[] {
                        ids}, this.PrjByIdsJsonOperationCompleted, userState);
        }
        
        private void OnPrjByIdsJsonOperationCompleted(object arg) {
            if ((this.PrjByIdsJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrjByIdsJsonCompleted(this, new PrjByIdsJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProfileOfRsrJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProfileOfRsrJson(string id) {
            object[] results = this.Invoke("ProfileOfRsrJson", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProfileOfRsrJsonAsync(string id) {
            this.ProfileOfRsrJsonAsync(id, null);
        }
        
        /// <remarks/>
        public void ProfileOfRsrJsonAsync(string id, object userState) {
            if ((this.ProfileOfRsrJsonOperationCompleted == null)) {
                this.ProfileOfRsrJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProfileOfRsrJsonOperationCompleted);
            }
            this.InvokeAsync("ProfileOfRsrJson", new object[] {
                        id}, this.ProfileOfRsrJsonOperationCompleted, userState);
        }
        
        private void OnProfileOfRsrJsonOperationCompleted(object arg) {
            if ((this.ProfileOfRsrJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProfileOfRsrJsonCompleted(this, new ProfileOfRsrJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RsrByIdsJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RsrByIdsJson(string[] ids) {
            object[] results = this.Invoke("RsrByIdsJson", new object[] {
                        ids});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RsrByIdsJsonAsync(string[] ids) {
            this.RsrByIdsJsonAsync(ids, null);
        }
        
        /// <remarks/>
        public void RsrByIdsJsonAsync(string[] ids, object userState) {
            if ((this.RsrByIdsJsonOperationCompleted == null)) {
                this.RsrByIdsJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRsrByIdsJsonOperationCompleted);
            }
            this.InvokeAsync("RsrByIdsJson", new object[] {
                        ids}, this.RsrByIdsJsonOperationCompleted, userState);
        }
        
        private void OnRsrByIdsJsonOperationCompleted(object arg) {
            if ((this.RsrByIdsJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RsrByIdsJsonCompleted(this, new RsrByIdsJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RsrOnPrjJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RsrOnPrjJson(string id) {
            object[] results = this.Invoke("RsrOnPrjJson", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RsrOnPrjJsonAsync(string id) {
            this.RsrOnPrjJsonAsync(id, null);
        }
        
        /// <remarks/>
        public void RsrOnPrjJsonAsync(string id, object userState) {
            if ((this.RsrOnPrjJsonOperationCompleted == null)) {
                this.RsrOnPrjJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRsrOnPrjJsonOperationCompleted);
            }
            this.InvokeAsync("RsrOnPrjJson", new object[] {
                        id}, this.RsrOnPrjJsonOperationCompleted, userState);
        }
        
        private void OnRsrOnPrjJsonOperationCompleted(object arg) {
            if ((this.RsrOnPrjJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RsrOnPrjJsonCompleted(this, new RsrOnPrjJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RsrInOrgJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RsrInOrgJson(string id) {
            object[] results = this.Invoke("RsrInOrgJson", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RsrInOrgJsonAsync(string id) {
            this.RsrInOrgJsonAsync(id, null);
        }
        
        /// <remarks/>
        public void RsrInOrgJsonAsync(string id, object userState) {
            if ((this.RsrInOrgJsonOperationCompleted == null)) {
                this.RsrInOrgJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRsrInOrgJsonOperationCompleted);
            }
            this.InvokeAsync("RsrInOrgJson", new object[] {
                        id}, this.RsrInOrgJsonOperationCompleted, userState);
        }
        
        private void OnRsrInOrgJsonOperationCompleted(object arg) {
            if ((this.RsrInOrgJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RsrInOrgJsonCompleted(this, new RsrInOrgJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CollaborationOfRsrOnPrj1Json", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CollaborationOfRsrOnPrj1Json(string id) {
            object[] results = this.Invoke("CollaborationOfRsrOnPrj1Json", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CollaborationOfRsrOnPrj1JsonAsync(string id) {
            this.CollaborationOfRsrOnPrj1JsonAsync(id, null);
        }
        
        /// <remarks/>
        public void CollaborationOfRsrOnPrj1JsonAsync(string id, object userState) {
            if ((this.CollaborationOfRsrOnPrj1JsonOperationCompleted == null)) {
                this.CollaborationOfRsrOnPrj1JsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCollaborationOfRsrOnPrj1JsonOperationCompleted);
            }
            this.InvokeAsync("CollaborationOfRsrOnPrj1Json", new object[] {
                        id}, this.CollaborationOfRsrOnPrj1JsonOperationCompleted, userState);
        }
        
        private void OnCollaborationOfRsrOnPrj1JsonOperationCompleted(object arg) {
            if ((this.CollaborationOfRsrOnPrj1JsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CollaborationOfRsrOnPrj1JsonCompleted(this, new CollaborationOfRsrOnPrj1JsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrgByRsrIdsJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OrgByRsrIdsJson(string[] ids) {
            object[] results = this.Invoke("OrgByRsrIdsJson", new object[] {
                        ids});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrgByRsrIdsJsonAsync(string[] ids) {
            this.OrgByRsrIdsJsonAsync(ids, null);
        }
        
        /// <remarks/>
        public void OrgByRsrIdsJsonAsync(string[] ids, object userState) {
            if ((this.OrgByRsrIdsJsonOperationCompleted == null)) {
                this.OrgByRsrIdsJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrgByRsrIdsJsonOperationCompleted);
            }
            this.InvokeAsync("OrgByRsrIdsJson", new object[] {
                        ids}, this.OrgByRsrIdsJsonOperationCompleted, userState);
        }
        
        private void OnOrgByRsrIdsJsonOperationCompleted(object arg) {
            if ((this.OrgByRsrIdsJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrgByRsrIdsJsonCompleted(this, new OrgByRsrIdsJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrgByIdJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OrgByIdJson(string ids) {
            object[] results = this.Invoke("OrgByIdJson", new object[] {
                        ids});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrgByIdJsonAsync(string ids) {
            this.OrgByIdJsonAsync(ids, null);
        }
        
        /// <remarks/>
        public void OrgByIdJsonAsync(string ids, object userState) {
            if ((this.OrgByIdJsonOperationCompleted == null)) {
                this.OrgByIdJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrgByIdJsonOperationCompleted);
            }
            this.InvokeAsync("OrgByIdJson", new object[] {
                        ids}, this.OrgByIdJsonOperationCompleted, userState);
        }
        
        private void OnOrgByIdJsonOperationCompleted(object arg) {
            if ((this.OrgByIdJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrgByIdJsonCompleted(this, new OrgByIdJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LecOfRsrJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LecOfRsrJson(string id) {
            object[] results = this.Invoke("LecOfRsrJson", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LecOfRsrJsonAsync(string id) {
            this.LecOfRsrJsonAsync(id, null);
        }
        
        /// <remarks/>
        public void LecOfRsrJsonAsync(string id, object userState) {
            if ((this.LecOfRsrJsonOperationCompleted == null)) {
                this.LecOfRsrJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLecOfRsrJsonOperationCompleted);
            }
            this.InvokeAsync("LecOfRsrJson", new object[] {
                        id}, this.LecOfRsrJsonOperationCompleted, userState);
        }
        
        private void OnLecOfRsrJsonOperationCompleted(object arg) {
            if ((this.LecOfRsrJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LecOfRsrJsonCompleted(this, new LecOfRsrJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CollaborationOfRsrOnBib1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode CollaborationOfRsrOnBib1(string id) {
            object[] results = this.Invoke("CollaborationOfRsrOnBib1", new object[] {
                        id});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void CollaborationOfRsrOnBib1Async(string id) {
            this.CollaborationOfRsrOnBib1Async(id, null);
        }
        
        /// <remarks/>
        public void CollaborationOfRsrOnBib1Async(string id, object userState) {
            if ((this.CollaborationOfRsrOnBib1OperationCompleted == null)) {
                this.CollaborationOfRsrOnBib1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCollaborationOfRsrOnBib1OperationCompleted);
            }
            this.InvokeAsync("CollaborationOfRsrOnBib1", new object[] {
                        id}, this.CollaborationOfRsrOnBib1OperationCompleted, userState);
        }
        
        private void OnCollaborationOfRsrOnBib1OperationCompleted(object arg) {
            if ((this.CollaborationOfRsrOnBib1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CollaborationOfRsrOnBib1Completed(this, new CollaborationOfRsrOnBib1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateIndexRsr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateIndexRsr(string indName) {
            this.Invoke("CreateIndexRsr", new object[] {
                        indName});
        }
        
        /// <remarks/>
        public void CreateIndexRsrAsync(string indName) {
            this.CreateIndexRsrAsync(indName, null);
        }
        
        /// <remarks/>
        public void CreateIndexRsrAsync(string indName, object userState) {
            if ((this.CreateIndexRsrOperationCompleted == null)) {
                this.CreateIndexRsrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateIndexRsrOperationCompleted);
            }
            this.InvokeAsync("CreateIndexRsr", new object[] {
                        indName}, this.CreateIndexRsrOperationCompleted, userState);
        }
        
        private void OnCreateIndexRsrOperationCompleted(object arg) {
            if ((this.CreateIndexRsrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateIndexRsrCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateIndexRsr_en", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateIndexRsr_en(string indName) {
            this.Invoke("CreateIndexRsr_en", new object[] {
                        indName});
        }
        
        /// <remarks/>
        public void CreateIndexRsr_enAsync(string indName) {
            this.CreateIndexRsr_enAsync(indName, null);
        }
        
        /// <remarks/>
        public void CreateIndexRsr_enAsync(string indName, object userState) {
            if ((this.CreateIndexRsr_enOperationCompleted == null)) {
                this.CreateIndexRsr_enOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateIndexRsr_enOperationCompleted);
            }
            this.InvokeAsync("CreateIndexRsr_en", new object[] {
                        indName}, this.CreateIndexRsr_enOperationCompleted, userState);
        }
        
        private void OnCreateIndexRsr_enOperationCompleted(object arg) {
            if ((this.CreateIndexRsr_enCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateIndexRsr_enCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateIndexPrj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateIndexPrj(string indName) {
            this.Invoke("CreateIndexPrj", new object[] {
                        indName});
        }
        
        /// <remarks/>
        public void CreateIndexPrjAsync(string indName) {
            this.CreateIndexPrjAsync(indName, null);
        }
        
        /// <remarks/>
        public void CreateIndexPrjAsync(string indName, object userState) {
            if ((this.CreateIndexPrjOperationCompleted == null)) {
                this.CreateIndexPrjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateIndexPrjOperationCompleted);
            }
            this.InvokeAsync("CreateIndexPrj", new object[] {
                        indName}, this.CreateIndexPrjOperationCompleted, userState);
        }
        
        private void OnCreateIndexPrjOperationCompleted(object arg) {
            if ((this.CreateIndexPrjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateIndexPrjCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateIndexPrj_en", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateIndexPrj_en(string indName) {
            this.Invoke("CreateIndexPrj_en", new object[] {
                        indName});
        }
        
        /// <remarks/>
        public void CreateIndexPrj_enAsync(string indName) {
            this.CreateIndexPrj_enAsync(indName, null);
        }
        
        /// <remarks/>
        public void CreateIndexPrj_enAsync(string indName, object userState) {
            if ((this.CreateIndexPrj_enOperationCompleted == null)) {
                this.CreateIndexPrj_enOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateIndexPrj_enOperationCompleted);
            }
            this.InvokeAsync("CreateIndexPrj_en", new object[] {
                        indName}, this.CreateIndexPrj_enOperationCompleted, userState);
        }
        
        private void OnCreateIndexPrj_enOperationCompleted(object arg) {
            if ((this.CreateIndexPrj_enCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateIndexPrj_enCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateIndexOrg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateIndexOrg(string indName) {
            this.Invoke("CreateIndexOrg", new object[] {
                        indName});
        }
        
        /// <remarks/>
        public void CreateIndexOrgAsync(string indName) {
            this.CreateIndexOrgAsync(indName, null);
        }
        
        /// <remarks/>
        public void CreateIndexOrgAsync(string indName, object userState) {
            if ((this.CreateIndexOrgOperationCompleted == null)) {
                this.CreateIndexOrgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateIndexOrgOperationCompleted);
            }
            this.InvokeAsync("CreateIndexOrg", new object[] {
                        indName}, this.CreateIndexOrgOperationCompleted, userState);
        }
        
        private void OnCreateIndexOrgOperationCompleted(object arg) {
            if ((this.CreateIndexOrgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateIndexOrgCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateAutocompleteFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateAutocompleteFile(string indName) {
            this.Invoke("CreateAutocompleteFile", new object[] {
                        indName});
        }
        
        /// <remarks/>
        public void CreateAutocompleteFileAsync(string indName) {
            this.CreateAutocompleteFileAsync(indName, null);
        }
        
        /// <remarks/>
        public void CreateAutocompleteFileAsync(string indName, object userState) {
            if ((this.CreateAutocompleteFileOperationCompleted == null)) {
                this.CreateAutocompleteFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAutocompleteFileOperationCompleted);
            }
            this.InvokeAsync("CreateAutocompleteFile", new object[] {
                        indName}, this.CreateAutocompleteFileOperationCompleted, userState);
        }
        
        private void OnCreateAutocompleteFileOperationCompleted(object arg) {
            if ((this.CreateAutocompleteFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAutocompleteFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PrjOfOrgJsonCompletedEventHandler(object sender, PrjOfOrgJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrjOfOrgJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrjOfOrgJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PrjOfRsrJsonCompletedEventHandler(object sender, PrjOfRsrJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrjOfRsrJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrjOfRsrJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PrjByRsrIdsJsonCompletedEventHandler(object sender, PrjByRsrIdsJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrjByRsrIdsJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrjByRsrIdsJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PrjByIdJsonCompletedEventHandler(object sender, PrjByIdJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrjByIdJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrjByIdJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PrjByIdsJsonCompletedEventHandler(object sender, PrjByIdsJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrjByIdsJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrjByIdsJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ProfileOfRsrJsonCompletedEventHandler(object sender, ProfileOfRsrJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProfileOfRsrJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProfileOfRsrJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RsrByIdsJsonCompletedEventHandler(object sender, RsrByIdsJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RsrByIdsJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RsrByIdsJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RsrOnPrjJsonCompletedEventHandler(object sender, RsrOnPrjJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RsrOnPrjJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RsrOnPrjJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RsrInOrgJsonCompletedEventHandler(object sender, RsrInOrgJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RsrInOrgJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RsrInOrgJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CollaborationOfRsrOnPrj1JsonCompletedEventHandler(object sender, CollaborationOfRsrOnPrj1JsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CollaborationOfRsrOnPrj1JsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CollaborationOfRsrOnPrj1JsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void OrgByRsrIdsJsonCompletedEventHandler(object sender, OrgByRsrIdsJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrgByRsrIdsJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrgByRsrIdsJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void OrgByIdJsonCompletedEventHandler(object sender, OrgByIdJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrgByIdJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrgByIdJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LecOfRsrJsonCompletedEventHandler(object sender, LecOfRsrJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LecOfRsrJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LecOfRsrJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CollaborationOfRsrOnBib1CompletedEventHandler(object sender, CollaborationOfRsrOnBib1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CollaborationOfRsrOnBib1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CollaborationOfRsrOnBib1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateIndexRsrCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateIndexRsr_enCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateIndexPrjCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateIndexPrj_enCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateIndexOrgCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateAutocompleteFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591